### ISSUE TITLE
Add delete endpoint

### ISSUE THREAD

**Issue by d3ck-org** [blockkeeper/blockkeeper-backend#3]
The API needs an endpoint for user deletion:

- URL: `DELETE https://.../user/<user_id>`
- Payload: `{_id: ..., userhash: ...}

Proposal:

- `_id` and `userhash` must match the database entries or deletion should be denied.
- First, the API deletes all related address entries.
- On success, the API deletes the user entry and returns 200.

**Comment by yeahoffline** [comment]
same for addresses ?

**Comment by d3ck-org** [comment]
See the "proposal" points ;)

**Comment by yeahoffline** [comment]
delete api is live. 
every user delete triggers delete addresses as well
