### ISSUE TITLE
Rate endpoint does not return all coin pairs

### ISSUE THREAD

**Issue by d3ck-org** [blockkeeper/blockkeeper-backend#5]
The rate endpoint response misses some coin pairs (at least EUR_CAD). The list should include all supported coins in both base-/quote-pair combinations and 1-to-1 mappings. E.g. for EUR, BTC, ETH:

- BTC_EUR
- EUR_BTC
- ETH_EUR
- EUR_ETH
- BTC_ETH
- ETH_BTC
- BTC_BTC
- EUR_EUR
- ETH_ETH

This is critical because a missing coin pair leads to an error in virtually every screen.

**Comment by yeahoffline** [comment]
adds more tsyms params to cryptocompare api call: f79c78df075c2a131ccb01db0a4e3535e18c540d
