### ISSUE TITLE
Rate endpoint returns sometimes null

### ISSUE THREAD

**Issue by d3ck-org** [blockkeeper/blockkeeper-backend#6]
Sometimes (not always) the rate call returns 200 but an empty response:

![screen2](https://user-images.githubusercontent.com/5405531/30552612-dd36b6c0-9c9e-11e7-832e-dde7c64ee62f.png)

![screen1](https://user-images.githubusercontent.com/5405531/30552611-dd31cbec-9c9e-11e7-96a6-714750c58404.png)

**Comment by yeahoffline** [comment]
the getRates endpoint now uses a internal table instead of an external api call against cryptocompare. 
519fa7edc0296038fdc9c01246f78cb2838a562f
the new updateRates function keeps the table up2date by checking the cryptocompare api every minute. 
6cda6b7b8dcef8b1e521d030e1a70443f7105c5b
