### ISSUE TITLE
Add CORS setting to Cloudfront errors

### ISSUE THREAD

**Issue by d3ck-org** [blockkeeper/blockkeeper-backend#8]
Upstream / Cloudfront errors miss the correct CORS setting. This results in an `No Access-Control-Allow-Origin header is present` browser failure. While this error is not critical, it is sometimes confusing during debugging processes.

![screen](https://user-images.githubusercontent.com/5405531/30826023-354efb38-a235-11e7-9924-5d181de0535a.png)

**Comment by yeahoffline** [comment]
cors headers added for http status 429
