### ISSUE TITLE
Add Get-User endpoint

### ISSUE THREAD

**Issue by d3ck-org** [blockkeeper/blockkeeper-backend#9]
The frontend framework relies on a generic loading process. This process fetchs the data from the API via a _Get-Resource_ (e.g. `GET /address/<user_id>`) request.

Because a _Get-User_ endpoint is missing, the `/login/<user_hash>` call is used instead. This works but breaks the generic framework workflow and is sometimes confusing (see e.g. https://github.com/blockkeeper/blockkeeper-frontend-web/issues/8).

A dedicated  `GET /user/<user_id>` would better support the standard framework behavior.

**Comment by yeahoffline** [comment]
live! 9b135e9d1b6636bf27cce077b5446b16aeaf170a
